# Generated by Django 5.0.4 on 2024-05-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='finallybudjet',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
