# Generated by Django 5.1 on 2024-08-19 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='timestamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 19, 18, 46, 8, 235501)),
        ),
    ]
