# Generated by Django 5.0.4 on 2024-04-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='lable',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
