# Generated by Django 5.1 on 2024-08-21 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_useractivity_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='client_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='timestamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 21, 15, 38, 34, 335865)),
        ),
    ]
