# Generated by Django 5.0.4 on 2024-07-05 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_customertable_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Fresh', 'Fresh'), ('Call Back', 'Call Back'), ('Do Not Disturb', 'Do Not Disturb'), ('Follow up', 'Follow up'), ('Proposed', 'Proposed'), ('Not Interested', 'Not Interested'), ('Hold', 'Hold'), ('Closed', 'Closed')], max_length=15),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='timestamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 7, 5, 15, 40, 7, 542892)),
        ),
    ]
