# Generated by Django 5.0.4 on 2024-05-29 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_useractivity_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='timestamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 29, 10, 59, 4, 684960)),
        ),
    ]
