# Generated by Django 5.0.4 on 2024-05-29 10:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_useractivity_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='remarks',
            new_name='additional_remarks',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='follow_up',
            new_name='call_back',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='comment',
            new_name='call_back_comments',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='org_img',
            new_name='company_img',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='org_name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='org_type',
            new_name='company_type',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='location',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='finallybudjet',
            new_name='finally_budjet',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='amount',
            new_name='proposal_amount',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='lead_name',
        ),
        migrations.AddField(
            model_name='lead',
            name='reffral_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontend.leadtable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='timestamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 29, 15, 41, 38, 379307)),
        ),
    ]
