# Generated by Django 5.0.4 on 2024-05-29 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_rename_remarks_lead_additional_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='timestamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 29, 15, 42, 22, 527469)),
        ),
    ]
